### ISSUE TITLE
Add search suggestions.

### ISSUE THREAD

**Issue by s3rius** [s3rius/feedEm#29]
Add REST API for search suggestions. 
Best implementation will be:
1. Frontend sends you a request with search query.  
2. Backend returns possible suggestions with suggested item type.
As example:
Sent by frontend: 
```
{
  "query": "pe"
}
```
Backend response:
```json
[
  {
    "suggest": "pepperoni",
    "type": "Order item"
  },
  {
    "suggest": "Peaks Island",
    "type": "Seller"
  }
]
```

**Comment by Kolaer** [comment]
Added simple search API at /search_api/search.

Parameters:
* query: string. String to query to.
* limit: integer. Limit to number of items. Works independently for each search type (Sellers, Merch.).

Result: json in this format:
* res: string. If it's "ok", then query results are in data, otherwise res is description of error.
* data: array of maps. Array of query's results.
   Each element contains:
   * suggest: string. Contains value to suggest.
   * type: string. Type of suggested item (Seller, Merch.).
